
# Name of the application
name = "random"

# Task-includes that the task inherits.
# Includes are specified in the format <filepath>#<ID>.
# Paths are relative to the application directory.
#. Valid variables: $ROOT.
# includes = []

[[Task]]

  # Identifies the task, currently the name must be 'build'.
  name = "build"

  # Command to execute. The command is run via the sh shell.
  command = "./build.sh build"

  # Input or Output includes that the task inherits.
  # Includes are specified in the format <filepath>#<ID>.
  # Paths are relative to the application directory.
  #. Valid variables: $ROOT.
  includes = ["$ROOT/baur-includes/build-inputs.toml#build-sh"]

    # Inputs specified by directories containing Golang applications
    [Task.Input.GolangSources]

      # Environment to use when discovering Golang source files
      # This can be environment variables understood by the Golang tools, like GOPATH, GOFLAGS, etc.
      # If empty the default Go environment is used.
      # Valid variables: $ROOT, $APPNAME
      environment = ["GOFLAGS=-mod=vendor","GO111MODULE=on"]

      # Paths to directories containing Golang source files.
      # All source files including imported packages are discovered,
      # files from Go's stdlib package and testfiles are ignored. Valid variables: $ROOT, $APPNAME.
      paths = ["."]


[[Task]]
  name = "check"

  command = "./build.sh check"
  includes = ["$ROOT/baur-includes/build-inputs.toml#build-sh"]

    [Task.Input.GolangSources]

      # Environment to use when discovering Golang source files
      # This can be environment variables understood by the Golang tools, like GOPATH, GOFLAGS, etc.
      # If empty the default Go environment is used.
      # Valid variables: $ROOT, $APPNAME
      environment = ["GOFLAGS=-mod=vendor","GO111MODULE=on"]

      # Paths to directories containing Golang source files.
      # All source files including imported packages are discovered,
      # files from Go's stdlib package and testfiles are ignored. Valid variables: $ROOT, $APPNAME.
      paths = ["."]
