
# Name of the application
name = "unixtime"

[[Task]]

  # Identifies the task, currently the name must be 'build'.
  name = "build"

  # Command to execute. The command is run via the sh shell.
  command = "make clean docker_build"

  # Specification of task inputs like source files, Makefiles, etc
  [Task.Input]

    [Task.Input.GitFiles]

      # Relative paths to source files.
      # Only files tracked by Git that are not in the .gitignore file are matched.
      # The same patterns that git ls-files supports can be used.
      # Valid variables: $ROOT, $APPNAME.
      paths = ["*.c", "Makefile"]

  # Specification of task outputs produced by the Task.command
  [Task.Output]

    [[Task.Output.File]]

      # Path relative to the application directory.
      # Valid variables: $ROOT, $APPNAME, $GITCOMMIT.
      path = "dist/unixtime"

      # Copy the file to a local directory.
      [Task.Output.File.FileCopy]

        # Destination directory
        # Valid variables: $ROOT, $APPNAME, $GITCOMMIT, $UUID.
        path = "/tmp/baur_build_artifacts/$APPNAME-$GITCOMMIT"
