
# Name of the application
name = "hello-server"

# Task-includes that the task inherits.
# Includes are specified in the format <filepath>#<ID>.
# Paths are relative to the application directory.
#. Valid variables: $ROOT.
includes = ["$ROOT/baur-includes/go-build.toml#build"]
